"""
Country name to code mappings.
"""

COUNTRY_MAPPING = {
    "Albania": "AL",
    "Armenia": "AM",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Belgium": "BE",
    "Bosnia and Herzegovina": "BA",
    "Bulgaria": "BG",
    "Croatia": "HR",
    "Cyprus": "CY",
    "Germany": "DE",
    "Serbia": "RS",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Czech Republic": "CZ",
    "Greece": "GR",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Italy": "IT",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Latvia": "LV",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Moldova": "MD",
    "Montenegro": "ME",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Russia": "RU",
    "Spain": "ES",
    "Sweden": "SE",
    "Switzerland": "CH",
    "the Netherlands": "NL",
    "Türkiye": "TR",
    "UK": "GB",
    "Ukraine": "UA",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Georgia": "GE"
}